import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "./components/AppWalletProvider";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import "simplebar-react/dist/simplebar.min.css";
import "react-toastify/dist/ReactToastify.css";
import { AppProvider } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWalletProvider>
          <AppProvider>
            <NextUIProvider>
              <ToastContainer />
              {children}
            </NextUIProvider>
          </AppProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
